font:
  size: 10.5
  normal:
    family: Fira Code Nerd Font
    style: Regular
  bold:
    family: Fira Code Nerd Font
    style: Bold
  # italic:
  #   family: Fira Code Nerd Font
  #   style: Bold Italic
  # bold_italic:
  #   family: Fira Code Nerd Font
  #   style: Bold Italic
  # offset:
  #   x: 0
  #   y: 3

tabspaces: 2

window:
  decorations: none
  padding:
    x: 4
    y: 2

mouse:
  hide_when_typing: true

colors:
  cursor:
    text:   '#000000'
    cursor: '#dddddd'

  primary:
    background: '#111111'
    foreground: '#dddddd'

  normal:
    black:   '#555555'
    red:     '#ff1111'
    green:   '#3fff3f'
    yellow:  '#ed9d12'
    blue:    '#5f87af'
    magenta: '#f92672'
    cyan:    '#66d9ef'
    white:   '#dddddd'

  bright:
    black:   '#5f87af'
    red:     '#ff3f3f'
    green:   '#3fff3f'
    yellow:  '#deed12'
    blue:    '#5f87af'
    magenta: '#f92672'
    cyan:    '#66d9ef'
    white:   '#dddddd'
