env:
  TERM: xterm-256color

font:
  size: 9
  normal:
    family: FiraMono Nerd Font Mono
    style: Regular
    # family: SauceCodePro Nerd Font Mono
    # style: Medium
  bold:
    family: FiraMono Nerd Font Mono
    # family: SauceCodePro Nerd Font Mono
    style: Bold
  italic:
    family: FiraMono Nerd Font Mono
    # family: SauceCodePro Nerd Font Mono
    style: Italic
  bold_italic:
    family: FiraMono Nerd Font Mono
    # family: SauceCodePro Nerd Font Mono
    style: Bold Italic
  offset:
    x: 0
    y: 0

# shell:
#     program: /usr/bin/tmux
#     args:
#      - -u # force UTF-8 in tmux
tabspaces: 2

windows:
  decorations: none
  padding:
    x: 2
    y: 2

mouse:
  hide_when_typing: true

colors:
  cursor:
    text:   '#000000'
    cursor: '#dddddd'

  primary:
    background: '#111111'
    foreground: '#dddddd'

  normal:
    black:   '#ffffff' # '#000000'
    red:     '#ff1111'
    green:   '#3fff3f'
    yellow:  '#ed9d12'
    blue:    '#5f87af'
    magenta: '#f92672'
    cyan:    '#66d9ef'
    white:   '#dddddd'

  bright:
    black:   '#ffffff' # '#5f87af'
    red:     '#ff3f3f'
    green:   '#3fff3f'
    yellow:  '#deed12'
    blue:    '#5f87af'
    magenta: '#f92672'
    cyan:    '#66d9ef'
    white:   '#dddddd'
