font:
  size: 9
  normal:
    family: Noto Sans Mono
  bold:
    family: Noto Sans Mono
  italic:
    family: Noto Sans Mono

# shell:
#     program: /usr/bin/tmux
#     args:
#      - -u # force UTF-8 in tmux

windows:
  decorations: none

mouse:
  hide_when_typing: true

colors:
  cursor:
      text:   '#000000'
      cursor: '#dddddd'

  primary:
    background: '#111111'
    foreground: '#dddddd'

  normal:
    black:   '#000000'
    red:     '#ff1111'
    green:   '#3fff3f'
    yellow:  '#ed9d12'
    blue:    '#5f87af'
    magenta: '#f92672'
    cyan:    '#66d9ef'
    white:   '#dddddd'

  bright:
    black:   '#1a1a1a'
    red:     '#ff3f3f'
    green:   '#3fff3f'
    yellow:  '#deed12'
    blue:    '#5f87af'
    magenta: '#f92672'
    cyan:    '#66d9ef'
    white:   '#dddddd'

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
