local function current_color()
  local row, col = unpack(vim.api.nvim_win_get_cursor(0))
  local id = vim.fn.synID(row, col, false)
  D(vim.fn.synIDattr(id, "name"))
end

vim.keymap.set({ "n", "x" }, "Q", "<CMD>qa<CR>", { desc = "quit neovim" })
vim.keymap.set({ "n", "x" }, "ö", "<CMD>noh<CR>", { desc = "clear selection" })
vim.keymap.set("x", "<", "<gv", { desc = "decrement indentation" })
vim.keymap.set("x", ">", ">gv", { desc = "increment indentation" })
vim.keymap.set({ "n", "x", "t" }, "<C-h>", "<CMD>wincmd h<CR>", { desc = "move to left window" })
vim.keymap.set({ "n", "x", "t" }, "<C-j>", "<CMD>wincmd j<CR>", { desc = "move to window below" })
vim.keymap.set({ "n", "x", "t" }, "<C-k>", "<CMD>wincmd k<CR>", { desc = "move to window above" })
vim.keymap.set({ "n", "x", "t" }, "<C-l>", "<CMD>wincmd l<CR>", { desc = "move to right window" })
vim.keymap.set({ "i" }, "<C-h>", "<ESC>:wincmd h<CR>", { desc = "move to left window" })
vim.keymap.set({ "i" }, "<C-j>", "<ESC>:wincmd j<CR>", { desc = "move to window below" })
vim.keymap.set({ "i" }, "<C-k>", "<ESC>:wincmd k<CR>", { desc = "move to window above" })
vim.keymap.set({ "i" }, "<C-l>", "<ESC>:wincmd l<CR>", { desc = "move to right window" })
vim.keymap.set({ "n", "x" }, "<left>", "<CMD>wincmd H<CR>", { desc = "swap with left window" })
vim.keymap.set({ "n", "x" }, "<right>", "<CMD>wincmd L<CR>", { desc = "swap with window below" })
vim.keymap.set({ "n", "x" }, "<up>", "<CMD>wincmd K<CR>", { desc = "swap with window above" })
vim.keymap.set({ "n", "x" }, "<down>", "<CMD>wincmd J<CR>", { desc = "swap with right window" })
vim.keymap.set("n", "db", "dvb", { desc = "delete word backwards" })
vim.keymap.set("n", "dB", "dvB", { desc = "delete word backwards with punctuation" })
vim.keymap.set("n", "cb", "cvb", { desc = "change word backwards" })
vim.keymap.set("n", "cB", "cvB", { desc = "change word backwards with punctuation" })
vim.keymap.set({ "n" }, "<space>ah", current_color, { desc = "show the highlighting group under the cursor" })
vim.keymap.set({ "n", "x" }, "gw", "<CMD>write<CR>", { desc = "write buffer changes" })
vim.keymap.set({ "n", "x" }, "gq", "gw", { desc = "break line" })
vim.keymap.set({ "n" }, "gqq", "gwl", { desc = "break line" })
vim.keymap.set({ "n", "x" }, "<space>tw", "<CMD>set wrap!<CR>", { desc = "write buffer changes" })
vim.keymap.set("n", "<space>cw", function()
  vim.cmd("cd %:p:h")
end, { desc = "change directory to current file" })
