local map = vim.api.nvim_set_keymap

map("n", "*", "<Plug>(asterisk-*)", {})
map("n", "#", "<Plug>(asterisk-#)", {})
map("n", "g*", "<Plug>(asterisk-g*)", {})
map("n", "g#", "<Plug>(asterisk-g#)", {})
map("n", "z*", "<Plug>(asterisk-z*)", {})
map("n", "gz*", "<Plug>(asterisk-gz*)", {})
map("n", "z#", "<Plug>(asterisk-z#)", {})
map("n", "gz#", "<Plug>(asterisk-gz#)", {})
map("x", "*", "<Plug>(asterisk-*)", {})
map("x", "#", "<Plug>(asterisk-#)", {})
map("x", "g*", "<Plug>(asterisk-g*)", {})
map("x", "g#", "<Plug>(asterisk-g#)", {})
map("x", "z*", "<Plug>(asterisk-z*)", {})
map("x", "gz*", "<Plug>(asterisk-gz*)", {})
map("x", "z#", "<Plug>(asterisk-z#)", {})
map("x", "gz#", "<Plug>(asterisk-gz#)", {})
