vim.keymap.set("", "<space>p", "<NOP>")
vim.keymap.set("", "<space>pi", ":PackerInstall<CR>")
vim.keymap.set("", "<space>pr", ":PackerClean<CR>")
vim.keymap.set("", "<space>pu", ":PackerUpdate<CR>")
vim.keymap.set("", "<space>pc", ":PackerCompile<CR>")
vim.keymap.set("", "<space>ps", ":PackerSync<CR>")
vim.keymap.set("", "<space>pp", ":PackerStatus<CR>")
vim.keymap.set("", "<space>pb", ":PackerCompile profile=true<CR>")
vim.keymap.set("", "<space>pv", ":PackerProfile<CR>")
