vim.keymap.set("", "<space>p", "<NOP>")
vim.keymap.set("", "<space>pi", "<CMD>PackerInstall<CR>")
vim.keymap.set("", "<space>pr", "<CMD>PackerClean<CR>")
vim.keymap.set("", "<space>pu", "<CMD>PackerUpdate<CR>")
vim.keymap.set("", "<space>pc", "<CMD>PackerCompile<CR>")
vim.keymap.set("", "<space>ps", "<CMD>PackerSync<CR>")
vim.keymap.set("", "<space>pp", "<CMD>PackerStatus<CR>")
vim.keymap.set("", "<space>pb", "<CMD>PackerCompile profile=true<CR>")
vim.keymap.set("", "<space>pv", "<CMD>PackerProfile<CR>")
